name: Android CI

on:
  pull_request:
    branches: [ master ]

jobs:
  Instrumented_tests:
    runs-on:  macOS-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run instrumented Tests
        uses: reactivecircus/android-emulator-runner@v1
        with:
          api-level: 29
          script: ./gradlew connectedCheck
